-- Os documentos legais oficiais são publicados pela migration
-- 20260828210645_publish_initial_production_legal_documents.sql.
-- O seed permanece intencionalmente vazio: dados reais ou fictícios de clientes,
-- cobranças e documentos devem ser criados pelos testes isolados que os utilizam.
